
title: Faiyaz's Blog
email: FaiyazJambotkar@github.com
description: >- # this means to ignore newlines until "baseurl:"
  This is a piece of abstract art. May look messy to the normal eye, but it's not what it seems.   
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: twitterFaiyaz
github_username:  FaiyazJambotkar

# Build settings
theme: minima
plugins:
  - jekyll-feed

